---
name: reusable build
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: staging
    secrets:
      docker_token:
        required: true
    outputs:
      build_version: ${{ build.steps.version.outputs.build_version }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: generate version
        id: version
        run: |
          VERSION="V1.0-${GITHUB_SHA::7}"
          echo "build_version=$VERSION" >> $GITHUB_OUTPUT
      - name: build
        run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"
      - name: check docker token
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is set: false"
          fi
      - name: generate version string
        run: ech
